import React from 'react'

const about = () => {
  return (
    <div>
      About
    </div>
  )
}

export default about;

export const metadata = {
  title: "About Shinobi",
  description: "Generated by teamShinobi",
};