import React from 'react'
import Script from 'next/script';

const contact = () => {
  return (
    <div>
      <Script>
        {`alert("This is contact")`}
      </Script>
      Contact
    </div>
  )
}

export default contact;

export const metadata = {
  title: "Contact Shinobi",
  description: "Generated by teamShinobi",
};
